name: weighty
description: weight tracking and management app

version: 0.7.6+8

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Data
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.12

  # Utils
  equatable: ^2.0.3
  intl: ^0.17.0
  table_calendar: ^3.0.3
  fl_chart: ^0.41.0
  url_launcher: ^6.0.18
  package_info_plus: ^1.3.0
  page_transition: ^2.0.4
  permission_handler: ^8.3.0
  share_plus: ^3.0.4

  # BLoC
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1

  # UI
  numeric_keyboard: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/weighty_app_icon.png"

flutter:
  assets:
    - assets/weighty_app_icon.png
    - assets/weighty_logo_lightblue.png
    - assets/weighty_logo_white.png
    - assets/weighty_logo_name_white.png
    - assets/weighty_name_white.png

  uses-material-design: true