name: weighty
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Data
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  shared_preferences: ^2.0.6

  # Utils
  equatable: ^2.0.0
  intl: ^0.16.1
  table_calendar: ^2.3.3
  settings_ui: ^0.5.0
  numberpicker: ^1.3.0
  fl_chart: ^0.35.0
  percent_indicator: "^2.1.7+2"
  google_fonts: ^2.1.0

  # BLoC
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1

  #Icons
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.4

flutter:
  uses-material-design: true