name: weighty
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Data
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  shared_preferences: ^0.5.12

  # Utils
  equatable: ^2.0.0
  intl: ^0.16.1
  table_calendar: ^2.3.3
  settings_ui: ^0.5.0
  numberpicker: ^1.3.0
  fl_chart: ^0.35.0

  # BLoC
  flutter_bloc: ^6.1.1

  #Icons
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: 1.3.4+1
  hive_generator: ^0.7.3
  build_runner: ^1.10.1

flutter:
  fonts:
    - family: Proxima Nova
      fonts:
        - asset: fonts/ProximaNova-AltBold.otf
        - asset: fonts/ProximaNova-AltLight.otf
        - asset: fonts/ProximaNova-AltThin.otf
        - asset: fonts/ProximaNova-Black.otf
        - asset: fonts/ProximaNova-Bold.otf
        - asset: fonts/ProximaNova-Extrabold.otf
        - asset: fonts/ProximaNova-Regular.otf
        - asset: fonts/ProximaNova-Thin.otf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-LightItalic.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-BlackItalic.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-BoldItalic.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-ExtraLightItalic.ttf
        - asset: fonts/Poppins-Italic.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-LightItalic.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-MediumItalic.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Thin.ttf
        - asset: fonts/Poppins-ThinItalic.ttf

  uses-material-design: true