name: weighty
description: A new Flutter project.

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  # Data
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  shared_preferences: ^0.5.12

  # Utils
  equatable: ^1.2.5
  intl: ^0.16.1
  table_calendar: ^2.3.3
  settings_ui: ^0.5.0
  numberpicker: ^1.3.0

  # BLoC
  flutter_bloc: ^6.1.1

  #Icons
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: 1.3.4+1
  hive_generator: ^0.7.3
  build_runner: ^1.10.1

flutter:
  fonts:
    - family: Proxima Nova
      fonts:
        - asset: fonts/ProximaNova-AltBold.otf
        - asset: fonts/ProximaNova-AltLight.otf
        - asset: fonts/ProximaNova-AltThin.otf
        - asset: fonts/ProximaNova-Black.otf
        - asset: fonts/ProximaNova-Bold.otf
        - asset: fonts/ProximaNova-Extrabold.otf
        - asset: fonts/ProximaNova-Regular.otf
        - asset: fonts/ProximaNova-Thin.otf
  uses-material-design: true