name: weighty
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Data
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  shared_preferences: ^0.5.12

  # Utils
  equatable: ^2.0.0
  intl: ^0.16.1
  table_calendar: ^2.3.3
  settings_ui: ^0.5.0
  numberpicker: ^1.3.0
  fl_chart: ^0.35.0
  percent_indicator: "^2.1.7+2"
  google_fonts: ^1.1.0

  # BLoC
  flutter_bloc: ^6.1.1

  #Icons
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: 1.3.4+1
  hive_generator: ^0.7.3
  build_runner: ^1.10.1

flutter:
  uses-material-design: true